/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:6aaf8c51-17b7-4194-a60d-41aa7a25c0b8",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_yB9JFAJgP",
    "aws_user_pools_web_client_id": "khou5uaftjffo2j9aiiu7tmf3",
    "oauth": {},
    "aws_cognito_username_attributes": [
        "EMAIL"
    ],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "aws_user_files_s3_bucket": "spookystock60b04-dev",
    "aws_user_files_s3_bucket_region": "us-east-1"
};


export default awsmobile;
